services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3001:3001'
    volumes:
      - /usr/src/app/node_modules
  mongo:
    image: mongo
